ADD-ONU::OLTID=@IP,PONID=NA-NA-@SLOT-@PONID:CTAG::AUTHTYPE=LOID,ONUID=@LOID,NAME=@LOID,ONUTYPE=HG260;
CFG-ONUBW::OLTID=@IP,PONID=NA-NA-@SLOT-@PONID,ONUIDTYPE=LOID,ONUID=@LOID:CTAG::UPBW=FTTX_U_300M,DOWNBW=FTTX_D_1G;
ADD-PONVLAN::OLTID=@IP,PONID=NA-NA-@SLOT-@PONID,ONUIDTYPE=LOID,ONUID=@LOID:CTAG::SVLAN=@SVLAN,CVLAN=46,UV=46,SCOS=7,CCOS=7;
ADD-PONVLAN::OLTID=@IP,PONID=NA-NA-@SLOT-@PONID,ONUIDTYPE=LOID,ONUID=@LOID:CTAG::SVLAN=@SVLAN,CVLAN=45,UV=45,SCOS=5,CCOS=5;
ADD-PONVLAN::OLTID=@IP,PONID=NA-NA-@SLOT-@PONID,ONUIDTYPE=LOID,ONUID=@LOID:CTAG::SVLAN=@SVLAN,CVLAN=@CVLAN,UV=41,SCOS=0,CCOS=0;
ADD-LANIPTVPORT::OLTID=@IP,PONID=NA-NA-@SLOT-@PONID,ONUIDTYPE=LOID,ONUID=@LOID:CTAG::UV=50,MVLAN=50;
